CREATE TABLE
	users (
		id SERIAL PRIMARY KEY,
		name VARCHAR(255) NOT NULL,
		username VARCHAR(255) NOT NULL UNIQUE,
		password_hash VARCHAR(255) NOT NULL,
		role VARCHAR(50) NOT NULL DEFAULT 'user',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	);

CREATE TABLE
	user_profiles (
		id SERIAL PRIMARY KEY,
		user_id INT REFERENCES users (id) ON DELETE CASCADE,
		avatar_url VARCHAR(255) DEFAULT '',
		bio TEXT DEFAULT '',
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	);

CREATE TABLE
	chat_rooms (
		id SERIAL PRIMARY KEY,
		name VARCHAR(255) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	);

CREATE TABLE
	messages (
		id SERIAL PRIMARY KEY,
		sender_id INT REFERENCES users (id) ON DELETE CASCADE,
		receiver_id INT REFERENCES users (id) ON DELETE CASCADE,
		chat_room_id INT REFERENCES chat_rooms (id) ON DELETE CASCADE,
		content TEXT NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	);

CREATE TABLE
	chat_room_members (
		id SERIAL PRIMARY KEY,
		chat_room_id INT REFERENCES chat_rooms (id) ON DELETE CASCADE,
		user_id INT REFERENCES users (id) ON DELETE CASCADE,
		joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	);
